import { Service } from "@/types";
import {
  Bot,
  Cloud,
  Lock,
  PenTool,
  Rocket,
  ShieldCheck,
  Fingerprint,
  Bug,
  FileCode,
  FileWarning,
  RotateCcw,
  Speech,
  LineChart,
  MessageCircle,
  Repeat,
  ServerCog,
  CreditCard,
  Package,
  Smartphone,
  Megaphone,
  GaugeCircle,
  Users,
  Code,
  Settings,
  Cpu,
  Activity,
  DatabaseBackup,
  Stethoscope,
  ClipboardList,
  Shield,
  ShoppingCart,
} from "lucide-react";

export const services: Service[] = [
  {
    icon: PenTool,
    title: "UI/UX Design",
    items: [
      { icon: Users, desc: "Intuitive & Human-Centered Interfaces" },
      { icon: Smartphone, desc: "Responsive Web & Mobile Designs" },
      { icon: Rocket, desc: "High-Fidelity Prototyping" },
      { icon: FileCode, desc: "Visual Identity & Branding" },
      { icon: LineChart, desc: "User Journey Mapping" },
      { icon: Activity, desc: "A/B Testing & User Feedback Integration" },
    ],
  },
  {
    icon: Rocket,
    title: "Software MVP",
    items: [
      { icon: Rocket, desc: "Rapid Prototyping & Development" },
      { icon: Package, desc: "Market-Ready Core Feature Set" },
      { icon: ServerCog, desc: "Scalable Backend Infrastructure" },
      { icon: RotateCcw, desc: "Agile-Based Iterative Delivery" },
      { icon: GaugeCircle, desc: "Cost-Effective Launch Strategy" },
      { icon: Activity, desc: "User Testing & Early Validation" },
    ],
  },
  {
    icon: Lock,
    title: "Software Security",
    items: [
      { icon: ShieldCheck, desc: "End-To-End Encryption Protocols" },
      { icon: Fingerprint, desc: "Secure Authentication Systems" },
      { icon: Bug, desc: "Regular Vulnerability Assessments" },
      { icon: Shield, desc: "Compliance With Data Privacy Laws" },
      { icon: FileCode, desc: "Code Audits & Penetration Testing" },
      { icon: DatabaseBackup, desc: "Disaster Recovery & Backup Plans" },
    ],
  },
  {
    icon: Bot,
    title: "Integrate An AI Model",
    items: [
      { icon: Cpu, desc: "Custom AI Model Deployment" },
      { icon: Speech, desc: "Natural Language Processing Integration" },
      { icon: LineChart, desc: "Predictive Analytics & Machine Learning" },
      { icon: MessageCircle, desc: "AI-Powered Chat Bots & Assistants" },
      { icon: Repeat, desc: "Automation Of Repetitive Tasks" },
      { icon: Cloud, desc: "Scalable Cloud-Based AI Inference" },
    ],
  },
  {
    icon: Code,
    title: "Software Development",
    items: [
      { icon: FileCode, desc: "Custom Software Tailored To Business Goals" },
      { icon: Smartphone, desc: "Cross-Platform Web & Mobile Applications" },
      { icon: Cloud, desc: "Cloud-Native, Scalable Architecture" },
      { icon: Cpu, desc: "API-Driven Microservices Integration" },
      { icon: RotateCcw, desc: "Agile Methodology With DevOps Pipelines" },
      { icon: Activity, desc: "Automated Testing For Smooth Releases" },
    ],
  },
  {
    icon: ShoppingCart,
    title: "Scalable E-Commerce",
    items: [
      { icon: ShoppingCart, desc: "Custom Storefront Development" },
      { icon: CreditCard, desc: "Secure Payment Gateway Integration" },
      { icon: Package, desc: "Inventory & Order Management" },
      { icon: Smartphone, desc: "Mobile-Optimized Shopping Experience" },
      { icon: Megaphone, desc: "Marketing & SEO Tools" },
      { icon: GaugeCircle, desc: "Performance Tuning For High Traffic" },
    ],
  },
  {
    icon: Cloud,
    title: "Cloud Computing",
    items: [
      { icon: Cloud, desc: "AWS, Azure, & GCP Deployment" },
      { icon: ServerCog, desc: "Auto-Scaling Server Architecture" },
      { icon: Settings, desc: "CI/CD Pipelines & DevOps Setup" },
      { icon: Cpu, desc: "Containerization Using Docker/Kubernetes" },
      { icon: Activity, desc: "Real-Time Monitoring & Alerts" },
      { icon: DatabaseBackup, desc: "Backup & Disaster Recovery Solutions" },
    ],
  },
  {
    icon: Stethoscope,
    title: "Support & Maintenance",
    items: [
      { icon: RotateCcw, desc: "Preventive Care Through Regular Updates" },
      { icon: Bug, desc: "Bug Fixing And Quick Turnaround" },
      { icon: FileWarning, desc: "Adaptive Support For Platform Upgrades" },
      { icon: GaugeCircle, desc: "Performance Tuning & Monitoring" },
      { icon: Shield, desc: "Security Patching And Threat Management" },
      { icon: ClipboardList, desc: "Ongoing User Support & Documentation" },
    ],
  },
];
