apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-assignment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-assignment2
  template:
    metadata:
      labels:
        app: devops-assignment2
    spec:
      containers:
      - name: devops-assignment2
        image: flyingcodeman/devops-assignment2:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: devops-assignment2-service
spec:
  selector:
    app: devops-assignment2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer