export const technologies = [
  {
    title: "DevOps",
    text: "Get access to custom software for your unique needs including frontend and backend technology.",
    icon: "/images/features/code.svg",
    stack: [
      {
        title: "Amazon ECS",
        icon: "/images/technologies/cloud/Amazon-Elastic-Container-Service.svg",
      },
      {
        title: "Amazon Elastic",
        icon: "/images/technologies/cloud/Amazon-Elastic.svg",
      },
      { title: "Amazon S3", icon: "/images/technologies/cloud/Amazon-S3.svg" },
      { title: "Ansible", icon: "/images/technologies/cloud/Ansible.svg" },
      {
        title: "AWS DynamoDB",
        icon: "/images/technologies/cloud/AWS-DynamoDB.svg",
      },
      { title: "AWS", icon: "/images/technologies/cloud/AWS.svg" },
      {
        title: "Azure Blob Storage",
        icon: "/images/technologies/cloud/Azure-Blob-Storage.svg",
      },
      {
        title: "Azure Data Lake",
        icon: "/images/technologies/cloud/Azure-Data-Lake.svg",
      },
      {
        title: "Azure DevOps",
        icon: "/images/technologies/cloud/Azure-DevOps.svg",
      },
      {
        title: "Azure Functions",
        icon: "/images/technologies/cloud/Azure-Functions.svg",
      },
      {
        title: "Azure IoT Hub",
        icon: "/images/technologies/cloud/Azure-IoT-Hub.svg",
      },
      {
        title: "Azure Notification Hub",
        icon: "/images/technologies/cloud/Azure-Notification-Hub.svg",
      },
      {
        title: "Azure Pipeline",
        icon: "/images/technologies/cloud/azure-pipline.svg",
      },
      {
        title: "Azure SQL Database",
        icon: "/images/technologies/cloud/Azure-SQL-Database.svg",
      },
      {
        title: "Azure Web Apps",
        icon: "/images/technologies/cloud/Azure-Web-Apps.svg",
      },
      {
        title: "DigitalOcean",
        icon: "/images/technologies/cloud/DigitalOcean.svg",
      },
      { title: "Docker", icon: "/images/technologies/cloud/Docker.svg" },
      { title: "Droplets", icon: "/images/technologies/cloud/Droplets.svg" },
      {
        title: "Google BigTable",
        icon: "/images/technologies/cloud/Google-BigTable.svg",
      },
      {
        title: "Google Cloud Datastore",
        icon: "/images/technologies/cloud/Google-Cloud-Datastore.svg",
      },
      {
        title: "Google Cloud IoT",
        icon: "/images/technologies/cloud/Google-Cloud-IoT.svg",
      },
      {
        title: "Google Cloud Platform",
        icon: "/images/technologies/cloud/Google-Cloud-Platform-GCP.svg",
      },
      {
        title: "Google Cloud SQL",
        icon: "/images/technologies/cloud/Google-Cloud-SQL.svg",
      },
      {
        title: "Kubernetes",
        icon: "/images/technologies/cloud/Kubernetes.svg",
      },
      {
        title: "Microsoft Azure App Insights",
        icon: "/images/technologies/cloud/Microsoft-Azure-Application-Insights.svg",
      },
      {
        title: "Microsoft Azure",
        icon: "/images/technologies/cloud/Microsoft-Azure.svg",
      },
      { title: "OpenShift", icon: "/images/technologies/cloud/OpenShift.svg" },
      {
        title: "PowerShell",
        icon: "/images/technologies/cloud/PowerShell.svg",
      },
      { title: "Terraform", icon: "/images/technologies/cloud/Terraform.svg" },
      { title: "Tesseract", icon: "/images/technologies/cloud/Tesseract.svg" },
      {
        title: "Virtual Machine",
        icon: "/images/technologies/cloud/Virtual-Machine.svg",
      },
    ],
    tech: [
      {
        title: "CI/CD & Automation",
        tools: [
          "GitHub Actions",
          "Gitlab CI",
          "CircleCI",
          "Jenkins",
          "TeamCity",
          "Drone CI",
          "Ansible",
          "Puppet",
          "Chef",
          "SaltStack",
          "Terraform",
          "Pulumi",
        ],
      },
      {
        title: "Containers & Orchestration",
        tools: [
          "Docker",
          "Docker Compose",
          "Kubernetes",
          "Helm",
          "OpenShift",
          "Rancher",
        ],
      },
      {
        title: "Monitoring & Logging",
        tools: [
          "Prometheus",
          "Grafana",
          "Datadog",
          "ELK Stack",
          "New Relic",
          "Sentry",
          "Logstash",
          "Fluentd",
        ],
      },
      {
        title: "Cloud Providers",
        tools: [
          "AWS",
          "Azure",
          "Google Cloud",
          "DigitalOcean",
          "Linode",
          "Heroku",
          "Vultr",
          "Netlify",
          "Vercel",
          "Render",
        ],
      },
      {
        title: "Cloud & Hosting",
        tools: [
          "AWS",
          "Azure",
          "Google Cloud",
          "DigitalOcean",
          "Heroku",
          "Netlify",
          "Vercel",
          "Linode",
          "Cloudflare",
        ],
      },
    ],
  },
  {
    title: "Integrations",
    text: "Immersive solutions behind the physical and virtual world offering customized experiences across various industries.",
    icon: "/images/features/vr.svg",
    stack: [
      {
        title: "Google Analytics",
        icon: "/images/features/intgrtion/Google logo.svg",
      },
      { title: "Hotjar", icon: "/images/features/intgrtion/Hotjar logo.svg" },
      { title: "Mobile", icon: "/images/features/intgrtion/Mollie logo.svg" },
      { title: "Paypal", icon: "/images/features/intgrtion/Paypal logo.svg" },
      { title: "Stripe", icon: "/images/features/intgrtion/Stripe logo.svg" },
    ],
    tech: [
      {
        title: "Payments",
        tools: [
          "Stripe",
          "Paypal",
          "Mollie",
          "Square",
          "Braintree",
          "Razorpay",
          "Adyen",
        ],
      },
      {
        title: "Analytics & Marketing",
        tools: [
          "Google Analytics",
          "Hotjar",
          "Mixpanel",
          "Segment",
          "Amplitude",
          "Heap",
          "Crisp",
          "Intercom",
          "Meta Pixel",
        ],
      },
      {
        title: "Communication",
        tools: [
          "Twilio",
          "SendGrid",
          "Postmark",
          "Mailgun",
          "Pusher",
          "PubNub",
          "Firebase Cloud Messaging",
        ],
      },
      {
        title: "CMS & Headless",
        tools: [
          "Strapi",
          "Sanity",
          "Contentful",
          "Ghost",
          "Directus",
          "Prismic",
          "KeystoneJS",
        ],
      },
    ],
  },
  {
    title: "Front-End",
    text: "Create top-rated UI solutions that offer personalized user experience with quality generated content.",
    icon: "/images/features/searchstar.svg",
    stack: [
      { title: "Angular", icon: "/images/technologies/frontend/Angular.svg" },
      {
        title: "Ant Design",
        icon: "/images/technologies/frontend/Ant-Design.svg",
      },
      {
        title: "Apollo GraphQL",
        icon: "/images/technologies/frontend/Apollo-GraphQL.svg",
      },
      {
        title: "Bootstrap",
        icon: "/images/technologies/frontend/Bootstrap.svg",
      },
      { title: "CSS", icon: "/images/technologies/frontend/CSS.svg" },
      { title: "Cypress", icon: "/images/technologies/frontend/cypress.svg" },
      { title: "Formly", icon: "/images/technologies/frontend/Formly.svg" },
      { title: "Gulp", icon: "/images/technologies/frontend/Gulp.svg" },
      { title: "Ionic", icon: "/images/technologies/frontend/Ionic.svg" },
      { title: "Jasmine", icon: "/images/technologies/frontend/Jasmine.svg" },
      {
        title: "JavaScript",
        icon: "/images/technologies/frontend/JavaScript.svg",
      },
      { title: "Jest", icon: "/images/technologies/frontend/Jest.svg" },
      { title: "Karma", icon: "/images/technologies/frontend/Karma.svg" },
      { title: "Lerna", icon: "/images/technologies/frontend/Lerna.svg" },
      { title: "LESS", icon: "/images/technologies/frontend/LESS.svg" },
      { title: "Lodash", icon: "/images/technologies/frontend/Lodash.svg" },
      { title: "Material", icon: "/images/technologies/frontend/Material.svg" },
      { title: "MobX", icon: "/images/technologies/frontend/MobX.svg" },
      { title: "Mocha", icon: "/images/technologies/frontend/Mocha.svg" },
      { title: "NextJS", icon: "/images/technologies/frontend/NextJS.svg" },
      { title: "NgRx", icon: "/images/technologies/frontend/NgRx.svg" },
      { title: "NGXS", icon: "/images/technologies/frontend/NGXS.svg" },
      { title: "NuxtJS", icon: "/images/technologies/frontend/NuxtJS.svg" },
      {
        title: "Protractor",
        icon: "/images/technologies/frontend/Protractor.svg",
      },
      { title: "PWA", icon: "/images/technologies/frontend/PWA.svg" },
      { title: "React", icon: "/images/technologies/frontend/React.svg" },
      { title: "Redux", icon: "/images/technologies/frontend/Redux.svg" },
      { title: "RxJS", icon: "/images/technologies/frontend/RxJS.svg" },
      { title: "SASS", icon: "/images/technologies/frontend/SASS.svg" },
      { title: "Stylus", icon: "/images/technologies/frontend/Stylus.svg" },
      { title: "Svelte", icon: "/images/technologies/frontend/Svelte.svg" },
      {
        title: "TypeScript",
        icon: "/images/technologies/frontend/TypeScript-1.svg",
      },
      {
        title: "Vue Router",
        icon: "/images/technologies/frontend/Vue-Router.svg",
      },
      { title: "Vuex", icon: "/images/technologies/frontend/Vuex.svg" },
      { title: "Webpack", icon: "/images/technologies/frontend/Webpack.svg" },
      {
        title: "WebSocket",
        icon: "/images/technologies/frontend/WebSocket.svg",
      },
    ],

    tech: [
      {
        title: "React",
        tools: [
          "React",
          "Next.js",
          "React Router",
          "Redux",
          "Redux Toolkit",
          "MobX",
          "Zustand",
          "RTK Query",
          "TRPC",
          "SWR",
          "Apollo Client",
          "Recoil",
          "React Query",
        ],
      },
      {
        title: "Angular",
        tools: [
          "Angular",
          "Angular Material",
          "KendoUI",
          "PrimeNG",
          "NgRx",
          "Akita",
          "RxJS",
        ],
      },
      {
        title: "Vue.js",
        tools: [
          "Vue",
          "NuxtJS",
          "Pinia",
          "Vue Router",
          "Vuetify",
          "Vitest",
          "VueUse",
          "Vite",
          "Quasar",
          "Element Plus",
        ],
      },
      {
        title: "Styling",
        tools: [
          "CSS3",
          "SASS",
          "LESS",
          "Tailwind CSS",
          "Bootstrap",
          "Material UI",
          "Styled Components",
          "Emotion",
          "Chakra UI",
        ],
      },
      {
        title: "Testing",
        tools: [
          "Jest",
          "Cypress",
          "Playwright",
          "Vitest",
          "React Testing Library",
          "Enzyme",
        ],
      },
    ],
  },
  {
    title: "Back-End",
    text: "Develop user-friendly experiences with server-oriented applications that cater to changing market needs and robust user convenience.",
    icon: "/images/features/android.svg",
    stack: [
      { title: "ASP.Net", icon: "/images/technologies/backend/ASP.Net_.svg" },
      { title: "Asyncio", icon: "/images/technologies/backend/Asyncio.svg" },
      { title: "AWS", icon: "/images/technologies/backend/AWS.svg" },
      { title: "Blender", icon: "/images/technologies/backend/Blender.svg" },
      { title: "Bottle", icon: "/images/technologies/backend/Bottle.svg" },
      { title: "C (1)", icon: "/images/technologies/backend/C (1).svg" },
      { title: "C", icon: "/images/technologies/backend/c.svg" },
      { title: "COBOL", icon: "/images/technologies/backend/cobol.svg" },
      { title: "Core", icon: "/images/technologies/backend/Core.svg" },
      { title: "Dash", icon: "/images/technologies/backend/Dash.svg" },
      { title: "Django", icon: "/images/technologies/backend/Django.svg" },
      {
        title: "Docker Compose",
        icon: "/images/technologies/backend/docker-compose.svg",
      },
      { title: "Drupal", icon: "/images/technologies/backend/Drupal.svg" },
      { title: "Falcon", icon: "/images/technologies/backend/Falcon.svg" },
      { title: "Flask", icon: "/images/technologies/backend/Flask.svg" },
      { title: "Go", icon: "/images/technologies/backend/Go.svg" },
      { title: "Java", icon: "/images/technologies/backend/Java.svg" },
      { title: "Laravel", icon: "/images/technologies/backend/Laravel.svg" },
      { title: "MongoDB", icon: "/images/technologies/backend/MongoDB.svg" },
      { title: "MySQL", icon: "/images/technologies/backend/MySQL.svg" },
      { title: "Node.js", icon: "/images/technologies/backend/Node.js.svg" },
      { title: "PHP", icon: "/images/technologies/backend/PHP.svg" },
      { title: "Python", icon: "/images/technologies/backend/Python.svg" },
      { title: "Redis", icon: "/images/technologies/backend/Redis.svg" },
      { title: "Ruby", icon: "/images/technologies/backend/Ruby.svg" },
      { title: "Rust", icon: "/images/technologies/backend/Rust.svg" },
      {
        title: "Spring Framework",
        icon: "/images/technologies/backend/Spring-Framework.svg",
      },
      { title: "Symfony", icon: "/images/technologies/backend/Symfony.svg" },
      { title: "Twisted", icon: "/images/technologies/backend/Twisted.svg" },
      { title: "Unity", icon: "/images/technologies/backend/unity.svg" },
      {
        title: "Unreal Engine",
        icon: "/images/technologies/backend/Unreal-Engine.svg",
      },
      {
        title: "WordPress",
        icon: "/images/technologies/backend/WordPress.svg",
      },
    ],
    tech: [
      {
        title: "Node.js",
        tools: [
          "Express.js",
          "NestJS",
          "Fastify",
          "Hapi.js",
          "Koa",
          "Prisma",
          "TypeORM",
          "Sequelize",
          "Socket.IO",
        ],
      },
      {
        title: "Ruby & Python",
        tools: [
          "Ruby on Rails",
          "Sinatra",
          "Hanami",
          "Django",
          "Flask",
          "FastAPI",
          "Tornado",
        ],
      },
      {
        title: "PHP & Java",
        tools: [
          "Laravel",
          "Symfony",
          "CodeIgniter",
          "Spring Boot",
          "Micronaut",
          "Quarkus",
        ],
      },
      {
        title: "Go & Others",
        tools: [
          "Gin",
          "Echo",
          "Buffalo",
          "Fiber (Go)",
          "ASP.NET Core",
          "Phoenix (Elixir)",
        ],
      },
    ],
  },
  {
    title: "Databases",
    text: "Through Machine Learning Algorithms and AI, we help businesses leverage technologies to drive automation and improve experiences.",
    icon: "/images/features/chip.svg",
    stack: [
      { title: "Postgres", icon: "/images/features/dtbase/postgres.svg" },
      { title: "Mysql", icon: "/images/features/dtbase/mysql.svg" },
      { title: "MongoDB", icon: "/images/features/dtbase/mongodb.svg" },
      { title: "Redis", icon: "/images/features/dtbase/redis.svg" },
      {
        title: "ElasticSeearch",
        icon: "/images/features/dtbase/elasticsearch.svg",
      },
      { title: "Firebase", icon: "/images/features/dtbase/firebase.svg" },
    ],
    tech: [
      {
        title: "SQL",
        tools: [
          "PostgreSQL",
          "MySQL",
          "MariaDB",
          "SQL Server",
          "SQLite",
          "CockroachDB",
        ],
      },
      {
        title: "NoSQL",
        tools: [
          "MongoDB",
          "CouchDB",
          "RethinkDB",
          "ArangoDB",
          "Amazon DynamoDB",
        ],
      },
      {
        title: "In-Memory / Search",
        tools: ["Redis", "Memcached", "ElasticSearch", "Typesense", "Solr"],
      },
      {
        title: "Realtime / Serverless",
        tools: [
          "Firebase Realtime DB",
          "Firestore",
          "Supabase",
          "Hasura",
          "FaunaDB",
        ],
      },
    ],
  },
];
