export const technologies = [
  {
    title: "DevOps",
    text: "Get access to custom software for your unique needs including frontend and backend technology.",
    icon: "/images/features/code.svg",
    stack: [
      { title: "Ansible", icon: "/images/features/devops/ansible.svg" },
      { title: "Chef", icon: "/images/features/devops/chef.svg" },
      { title: "Docker", icon: "/images/features/devops/ansible.svg" },
      { title: "Gitlab CI", icon: "/images/features/devops/gitlab.svg" },
      { title: "Ansiblee", icon: "/images/features/devops/ansible.svg" },
      { title: "Cheff", icon: "/images/features/devops/chef.svg" },
      { title: "Dockerr", icon: "/images/features/devops/ansible.svg" },
      { title: "Gitlab CII", icon: "/images/features/devops/gitlab.svg" },
      { title: "AWS", icon: "/images/features/infrastructure/aws.svg" },
      {
        title: "Digital Ocean",
        icon: "/images/features/infrastructure/docean.svg",
      },
      { title: "Heroku", icon: "/images/features/infrastructure/heroku.svg" },
    ],
    tech: [
      {
        title: "CI/CD & Automation",
        tools: [
          "GitHub Actions",
          "Gitlab CI",
          "CircleCI",
          "Jenkins",
          "TeamCity",
          "Drone CI",
          "Ansible",
          "Puppet",
          "Chef",
          "SaltStack",
          "Terraform",
          "Pulumi",
        ],
      },
      {
        title: "Containers & Orchestration",
        tools: [
          "Docker",
          "Docker Compose",
          "Kubernetes",
          "Helm",
          "OpenShift",
          "Rancher",
        ],
      },
      {
        title: "Monitoring & Logging",
        tools: [
          "Prometheus",
          "Grafana",
          "Datadog",
          "ELK Stack",
          "New Relic",
          "Sentry",
          "Logstash",
          "Fluentd",
        ],
      },
      {
        title: "Cloud Providers",
        tools: [
          "AWS",
          "Azure",
          "Google Cloud",
          "DigitalOcean",
          "Linode",
          "Heroku",
          "Vultr",
          "Netlify",
          "Vercel",
          "Render",
        ],
      },
      {
        title: "Cloud & Hosting",
        tools: [
          "AWS",
          "Azure",
          "Google Cloud",
          "DigitalOcean",
          "Heroku",
          "Netlify",
          "Vercel",
          "Linode",
          "Cloudflare",
        ],
      },
    ],
  },
  {
    title: "Integrations",
    text: "Immersive solutions behind the physical and virtual world offering customized experiences across various industries.",
    icon: "/images/features/vr.svg",
    stack: [
      {
        title: "Google Analytics",
        icon: "/images/features/intgrtion/Google logo.svg",
      },
      { title: "Hotjar", icon: "/images/features/intgrtion/Hotjar logo.svg" },
      { title: "Mobile", icon: "/images/features/intgrtion/Mollie logo.svg" },
      { title: "Paypal", icon: "/images/features/intgrtion/Paypal logo.svg" },
      { title: "Stripe", icon: "/images/features/intgrtion/Stripe logo.svg" },
    ],
    tech: [
      {
        title: "Payments",
        tools: [
          "Stripe",
          "Paypal",
          "Mollie",
          "Square",
          "Braintree",
          "Razorpay",
          "Adyen",
        ],
      },
      {
        title: "Analytics & Marketing",
        tools: [
          "Google Analytics",
          "Hotjar",
          "Mixpanel",
          "Segment",
          "Amplitude",
          "Heap",
          "Crisp",
          "Intercom",
          "Meta Pixel",
        ],
      },
      {
        title: "Communication",
        tools: [
          "Twilio",
          "SendGrid",
          "Postmark",
          "Mailgun",
          "Pusher",
          "PubNub",
          "Firebase Cloud Messaging",
        ],
      },
      {
        title: "CMS & Headless",
        tools: [
          "Strapi",
          "Sanity",
          "Contentful",
          "Ghost",
          "Directus",
          "Prismic",
          "KeystoneJS",
        ],
      },
    ],
  },
  {
    title: "Front-End",
    text: "Create top-rated UI solutions that offer personalized user experience with quality generated content.",
    icon: "/images/features/searchstar.svg",
    stack: [
      { title: "CSS 3", icon: "/images/features/frtend/css.svg" },
      { title: "HTML 5", icon: "/images/features/frtend/html.svg" },
      { title: "JS", icon: "/images/features/frtend/js.svg" },
      { title: "React", icon: "/images/features/frtend/react.svg" },
      { title: "Redux", icon: "/images/features/frtend/redux.svg" },
      { title: "Vue", icon: "/images/features/frtend/vue.svg" },
    ],
    tech: [
      {
        title: "React",
        tools: [
          "React",
          "Next.js",
          "React Router",
          "Redux",
          "Redux Toolkit",
          "MobX",
          "Zustand",
          "RTK Query",
          "TRPC",
          "SWR",
          "Apollo Client",
          "Recoil",
          "React Query",
        ],
      },
      {
        title: "Angular",
        tools: [
          "Angular",
          "Angular Material",
          "KendoUI",
          "PrimeNG",
          "NgRx",
          "Akita",
          "RxJS",
        ],
      },
      {
        title: "Vue.js",
        tools: [
          "Vue",
          "NuxtJS",
          "Pinia",
          "Vue Router",
          "Vuetify",
          "Vitest",
          "VueUse",
          "Vite",
          "Quasar",
          "Element Plus",
        ],
      },
      {
        title: "Styling",
        tools: [
          "CSS3",
          "SASS",
          "LESS",
          "Tailwind CSS",
          "Bootstrap",
          "Material UI",
          "Styled Components",
          "Emotion",
          "Chakra UI",
        ],
      },
      {
        title: "Testing",
        tools: [
          "Jest",
          "Cypress",
          "Playwright",
          "Vitest",
          "React Testing Library",
          "Enzyme",
        ],
      },
    ],
  },
  {
    title: "Back-End",
    text: "Develop user-friendly experiences with server-oriented applications that cater to changing market needs and robust user convenience.",
    icon: "/images/features/android.svg",
    stack: [
      { title: "Rails", icon: "/images/features/bcend/rails.svg" },
      { title: "Ruby on Rails", icon: "/images/features/bcend/ruby.svg" },
      { title: "Strapi", icon: "/images/features/bcend/strapi.svg" },
    ],
    tech: [
      {
        title: "Node.js",
        tools: [
          "Express.js",
          "NestJS",
          "Fastify",
          "Hapi.js",
          "Koa",
          "Prisma",
          "TypeORM",
          "Sequelize",
          "Socket.IO",
        ],
      },
      {
        title: "Ruby & Python",
        tools: [
          "Ruby on Rails",
          "Sinatra",
          "Hanami",
          "Django",
          "Flask",
          "FastAPI",
          "Tornado",
        ],
      },
      {
        title: "PHP & Java",
        tools: [
          "Laravel",
          "Symfony",
          "CodeIgniter",
          "Spring Boot",
          "Micronaut",
          "Quarkus",
        ],
      },
      {
        title: "Go & Others",
        tools: [
          "Gin",
          "Echo",
          "Buffalo",
          "Fiber (Go)",
          "ASP.NET Core",
          "Phoenix (Elixir)",
        ],
      },
    ],
  },
  {
    title: "Databases",
    text: "Through Machine Learning Algorithms and AI, we help businesses leverage technologies to drive automation and improve experiences.",
    icon: "/images/features/chip.svg",
    stack: [
      { title: "Postgres", icon: "/images/features/dtbase/postgres.svg" },
      { title: "Mysql", icon: "/images/features/dtbase/mysql.svg" },
      { title: "MongoDB", icon: "/images/features/dtbase/mongodb.svg" },
      { title: "Redis", icon: "/images/features/dtbase/redis.svg" },
      {
        title: "ElasticSeearch",
        icon: "/images/features/dtbase/elasticsearch.svg",
      },
      { title: "Firebase", icon: "/images/features/dtbase/firebase.svg" },
    ],
    tech: [
      {
        title: "SQL",
        tools: [
          "PostgreSQL",
          "MySQL",
          "MariaDB",
          "SQL Server",
          "SQLite",
          "CockroachDB",
        ],
      },
      {
        title: "NoSQL",
        tools: [
          "MongoDB",
          "CouchDB",
          "RethinkDB",
          "ArangoDB",
          "Amazon DynamoDB",
        ],
      },
      {
        title: "In-Memory / Search",
        tools: ["Redis", "Memcached", "ElasticSearch", "Typesense", "Solr"],
      },
      {
        title: "Realtime / Serverless",
        tools: [
          "Firebase Realtime DB",
          "Firestore",
          "Supabase",
          "Hasura",
          "FaunaDB",
        ],
      },
    ],
  },
];
