export const technologies = [
  {
    title: "Front-End",
    text: "Create top-rated UI solutions that offer personalized user experience with quality generated content.",
    icon: "/images/features/searchstar.svg",
    stack: [
      { title: "Angular", icon: "/images/technologies/frontend/Angular.svg" },
      {
        title: "Ant Design",
        icon: "/images/technologies/frontend/Ant-Design.svg",
      },
      {
        title: "Apollo GraphQL",
        icon: "/images/technologies/frontend/Apollo-GraphQL.svg",
      },
      {
        title: "Bootstrap",
        icon: "/images/technologies/frontend/Bootstrap.svg",
      },
      { title: "CSS", icon: "/images/technologies/frontend/CSS.svg" },
      { title: "Cypress", icon: "/images/technologies/frontend/cypress.svg" },
      { title: "Formly", icon: "/images/technologies/frontend/Formly.svg" },
      { title: "Gulp", icon: "/images/technologies/frontend/Gulp.svg" },
      { title: "Ionic", icon: "/images/technologies/frontend/Ionic.svg" },
      { title: "Jasmine", icon: "/images/technologies/frontend/Jasmine.svg" },
      {
        title: "JavaScript",
        icon: "/images/technologies/frontend/JavaScript.svg",
      },
      { title: "Jest", icon: "/images/technologies/frontend/Jest.svg" },
      { title: "Karma", icon: "/images/technologies/frontend/Karma.svg" },
      { title: "Lerna", icon: "/images/technologies/frontend/Lerna.svg" },
      { title: "LESS", icon: "/images/technologies/frontend/LESS.svg" },
      { title: "Lodash", icon: "/images/technologies/frontend/Lodash.svg" },
      { title: "Material", icon: "/images/technologies/frontend/Material.svg" },
      { title: "MobX", icon: "/images/technologies/frontend/MobX.svg" },
      { title: "Mocha", icon: "/images/technologies/frontend/Mocha.svg" },
      { title: "NextJS", icon: "/images/technologies/frontend/NextJS.svg" },
      { title: "NgRx", icon: "/images/technologies/frontend/NgRx.svg" },
      { title: "NGXS", icon: "/images/technologies/frontend/NGXS.svg" },
      { title: "NuxtJS", icon: "/images/technologies/frontend/NuxtJS.svg" },
      {
        title: "Protractor",
        icon: "/images/technologies/frontend/Protractor.svg",
      },
      { title: "PWA", icon: "/images/technologies/frontend/PWA.svg" },
      { title: "React", icon: "/images/technologies/frontend/React.svg" },
      { title: "Redux", icon: "/images/technologies/frontend/Redux.svg" },
      { title: "RxJS", icon: "/images/technologies/frontend/RxJS.svg" },
      { title: "SASS", icon: "/images/technologies/frontend/SASS.svg" },
      { title: "Stylus", icon: "/images/technologies/frontend/Stylus.svg" },
      { title: "Svelte", icon: "/images/technologies/frontend/Svelte.svg" },
      {
        title: "TypeScript",
        icon: "/images/technologies/frontend/TypeScript-1.svg",
      },
      {
        title: "Vue Router",
        icon: "/images/technologies/frontend/Vue-Router.svg",
      },
      { title: "Vuex", icon: "/images/technologies/frontend/Vuex.svg" },
      { title: "Webpack", icon: "/images/technologies/frontend/Webpack.svg" },
      {
        title: "WebSocket",
        icon: "/images/technologies/frontend/WebSocket.svg",
      },
    ],

    tech: [
      {
        title: "React",
        tools: [
          "React",
          "Next.js",
          "React Router",
          "Redux",
          "Redux Toolkit",
          "MobX",
          "Zustand",
          "RTK Query",
          "TRPC",
          "SWR",
          "Apollo Client",
          "Recoil",
          "React Query",
        ],
      },
      {
        title: "Angular",
        tools: [
          "Angular",
          "Angular Material",
          "KendoUI",
          "PrimeNG",
          "NgRx",
          "Akita",
          "RxJS",
        ],
      },
      {
        title: "Vue.js",
        tools: [
          "Vue",
          "NuxtJS",
          "Pinia",
          "Vue Router",
          "Vuetify",
          "Vitest",
          "VueUse",
          "Vite",
          "Quasar",
          "Element Plus",
        ],
      },
      {
        title: "Styling",
        tools: [
          "CSS3",
          "SASS",
          "LESS",
          "Tailwind CSS",
          "Bootstrap",
          "Material UI",
          "Styled Components",
          "Emotion",
          "Chakra UI",
        ],
      },
      {
        title: "Testing",
        tools: [
          "Jest",
          "Cypress",
          "Playwright",
          "Vitest",
          "React Testing Library",
          "Enzyme",
        ],
      },
    ],
  },
  {
    title: "Back-End",
    text: "Develop user-friendly experiences with server-oriented applications that cater to changing market needs and robust user convenience.",
    icon: "/images/features/android.svg",
    stack: [
      { title: "ASP.Net", icon: "/images/technologies/backend/ASP.Net_.svg" },
      { title: "Asyncio", icon: "/images/technologies/backend/Asyncio.svg" },
      { title: "AWS", icon: "/images/technologies/backend/AWS.svg" },
      { title: "Blender", icon: "/images/technologies/backend/Blender.svg" },
      { title: "Bottle", icon: "/images/technologies/backend/Bottle.svg" },
      { title: "C (1)", icon: "/images/technologies/backend/C (1).svg" },
      { title: "C", icon: "/images/technologies/backend/c.svg" },
      { title: "COBOL", icon: "/images/technologies/backend/cobol.svg" },
      { title: "Core", icon: "/images/technologies/backend/Core.svg" },
      { title: "Dash", icon: "/images/technologies/backend/Dash.svg" },
      { title: "Django", icon: "/images/technologies/backend/Django.svg" },
      {
        title: "Docker Compose",
        icon: "/images/technologies/backend/docker-compose.svg",
      },
      { title: "Drupal", icon: "/images/technologies/backend/Drupal.svg" },
      { title: "Falcon", icon: "/images/technologies/backend/Falcon.svg" },
      { title: "Flask", icon: "/images/technologies/backend/Flask.svg" },
      { title: "Go", icon: "/images/technologies/backend/Go.svg" },
      { title: "Java", icon: "/images/technologies/backend/Java.svg" },
      { title: "Laravel", icon: "/images/technologies/backend/Laravel.svg" },
      { title: "MongoDB", icon: "/images/technologies/backend/MongoDB.svg" },
      { title: "MySQL", icon: "/images/technologies/backend/MySQL.svg" },
      { title: "Node.js", icon: "/images/technologies/backend/Node.js.svg" },
      { title: "PHP", icon: "/images/technologies/backend/PHP.svg" },
      { title: "Python", icon: "/images/technologies/backend/Python.svg" },
      { title: "Redis", icon: "/images/technologies/backend/Redis.svg" },
      { title: "Ruby", icon: "/images/technologies/backend/Ruby.svg" },
      { title: "Rust", icon: "/images/technologies/backend/Rust.svg" },
      {
        title: "Spring Framework",
        icon: "/images/technologies/backend/Spring-Framework.svg",
      },
      { title: "Symfony", icon: "/images/technologies/backend/Symfony.svg" },
      { title: "Twisted", icon: "/images/technologies/backend/Twisted.svg" },
      { title: "Unity", icon: "/images/technologies/backend/unity.svg" },
      {
        title: "Unreal Engine",
        icon: "/images/technologies/backend/Unreal-Engine.svg",
      },
      {
        title: "WordPress",
        icon: "/images/technologies/backend/WordPress.svg",
      },
    ],
    tech: [
      {
        title: "Node.js",
        tools: [
          "Express.js",
          "NestJS",
          "Fastify",
          "Hapi.js",
          "Koa",
          "Prisma",
          "TypeORM",
          "Sequelize",
          "Socket.IO",
        ],
      },
      {
        title: "Ruby & Python",
        tools: [
          "Ruby on Rails",
          "Sinatra",
          "Hanami",
          "Django",
          "Flask",
          "FastAPI",
          "Tornado",
        ],
      },
      {
        title: "PHP & Java",
        tools: [
          "Laravel",
          "Symfony",
          "CodeIgniter",
          "Spring Boot",
          "Micronaut",
          "Quarkus",
        ],
      },
      {
        title: "Go & Others",
        tools: [
          "Gin",
          "Echo",
          "Buffalo",
          "Fiber (Go)",
          "ASP.NET Core",
          "Phoenix (Elixir)",
        ],
      },
    ],
  },
  {
    title: "Mobile",
    text: "Immersive solutions behind the physical and virtual world offering customized experiences across various industries.",
    icon: "/images/features/vr.svg",
    stack: [
      {
        title: "Alamofire",
        icon: "/images/technologies/mobile/Alamofire.svg",
      },
      {
        title: "Android",
        icon: "/images/technologies/mobile/android.svg",
      },
      {
        title: "Autofac",
        icon: "/images/technologies/mobile/Autofac.svg",
      },
      {
        title: "Bloc",
        icon: "/images/technologies/mobile/Bloc.svg",
      },
      {
        title: "Clean Swift",
        icon: "/images/technologies/mobile/Clean-Swift.svg",
      },
      {
        title: "Core",
        icon: "/images/technologies/mobile/Core.svg",
      },
      {
        title: "CoreLocation",
        icon: "/images/technologies/mobile/CoreLocation.svg",
      },
      {
        title: "Dagger2",
        icon: "/images/technologies/mobile/Dagger2.svg",
      },
      {
        title: "Dart Async",
        icon: "/images/technologies/mobile/Dart-async.svg",
      },
      {
        title: "Firebase",
        icon: "/images/technologies/mobile/Firebase.svg",
      },
      {
        title: "Flutter",
        icon: "/images/technologies/mobile/Flutter.svg",
      },
      {
        title: "GCD",
        icon: "/images/technologies/mobile/GCD.svg",
      },
      {
        title: "Hilt",
        icon: "/images/technologies/mobile/Hilt.svg",
      },
      {
        title: "iOS",
        icon: "/images/technologies/mobile/iOS.svg",
      },
      {
        title: "Java",
        icon: "/images/technologies/mobile/Java.svg",
      },
      {
        title: "JUnit",
        icon: "/images/technologies/mobile/JUnit.svg",
      },
      {
        title: "Kotlin",
        icon: "/images/technologies/mobile/Kotlin.svg",
      },
      {
        title: "LiveData",
        icon: "/images/technologies/mobile/LiveData.svg",
      },
      {
        title: "Mockito",
        icon: "/images/technologies/mobile/Mockito.svg",
      },
      {
        title: "MVP",
        icon: "/images/technologies/mobile/MVP.svg",
      },
      {
        title: "MVVM",
        icon: "/images/technologies/mobile/MVVM.svg",
      },
      {
        title: ".NET MAUI",
        icon: "/images/technologies/mobile/NET-MAUI.svg",
      },
      {
        title: "Objective-C",
        icon: "/images/technologies/mobile/Objective-C.svg",
      },
      {
        title: "React Native",
        icon: "/images/technologies/mobile/React-Native.svg",
      },
      {
        title: "React",
        icon: "/images/technologies/mobile/React.svg",
      },
      {
        title: "Redux Saga",
        icon: "/images/technologies/mobile/Redux-Saga.svg",
      },
      {
        title: "Redux",
        icon: "/images/technologies/mobile/Redux.svg",
      },
      {
        title: "REST API",
        icon: "/images/technologies/mobile/rest-api.svg",
      },
      {
        title: "Robolectric",
        icon: "/images/technologies/mobile/Robolectric.svg",
      },
      {
        title: "RxJS",
        icon: "/images/technologies/mobile/RxJS.svg",
      },
      {
        title: "Snap Kit",
        icon: "/images/technologies/mobile/Snap-Kit.svg",
      },
      {
        title: "SOAP API",
        icon: "/images/technologies/mobile/SOAP-API.svg",
      },
      {
        title: "SQLite",
        icon: "/images/technologies/mobile/Sqlite.svg",
      },
      {
        title: "Swift",
        icon: "/images/technologies/mobile/Swift.svg",
      },
      {
        title: "TypeScript",
        icon: "/images/technologies/mobile/TypeScript-1.svg",
      },
    ],
    tech: [
      {
        title: "iOS",
        tools: [
          "Swift",
          "Objective-C",
          "VIPER",
          "Clean Swift",
          "MVP",
          "MVVM",
          "MVC",
          "The Composable Architecture",
          "SwiftUI",
          "UIKit",
          "SnapKit",
          "XIB",
          "Swinject",
          "GCD",
          "Combine",
        ],
      },
      {
        title: "Android",
        tools: [
          "Kotlin",
          "Java MVP",
          "MVVM",
          "MVI",
          "Clean Architecture",
          "Multi-module architecture",
          "KMP",
          "Android SDK",
          "Android Studio",
          "Android NDK",
          "Jetpack toolkit",
        ],
      },
      {
        title: "Flutter",
        tools: [
          "Dart",
          "Clean Architecture",
          "BLoC",
          "MVVM",
          "Redux",
          "Flutter SDK",
          "Flutter Web",
          "Flutter Plugins",
          "Provider",
          "Flutter Async",
          "Streams",
          "RxDart",
          "GetIt",
          "Dio",
        ],
      },
      {
        title: "React Native",
        tools: [
          "React",
          "React-Native",
          "React-Navigation",
          "React Native Navigation",
          "Expo",
          "EAS",
          "Native Base",
          "React Native Camera",
          "Redux",
          "Redux Toolkit",
          "MobX",
          "Zustand",
        ],
      },
      {
        title: "Xamarin",
        tools: [
          "Xamarin.Native (Xamarin.iOS, Xamarin.Android, Xamarin.Mac)",
          "Electron",
          "Xamarin.Forms",
          "Xamarin.UWP",
          "Visual Studio",
          ".NET Core",
        ],
      },
      {
        title: ".NET MAUI",
        tools: [
          ".NET MAUI Blazor",
          ".NET Core",
          "REST/SOAP API backend",
          "SQLite",
          "XAML",
          "Autofac",
        ],
      },
    ],
  },
  {
    title: "DevOps",
    text: "Get access to custom software for your unique needs including frontend and backend technology.",
    icon: "/images/features/code.svg",
    stack: [
      {
        title: "Amazon ECS",
        icon: "/images/technologies/cloud/Amazon-Elastic-Container-Service.svg",
      },
      {
        title: "Amazon Elastic",
        icon: "/images/technologies/cloud/Amazon-Elastic.svg",
      },
      { title: "Amazon S3", icon: "/images/technologies/cloud/Amazon-S3.svg" },
      { title: "Ansible", icon: "/images/technologies/cloud/Ansible.svg" },
      {
        title: "AWS DynamoDB",
        icon: "/images/technologies/cloud/AWS-DynamoDB.svg",
      },
      { title: "AWS", icon: "/images/technologies/cloud/AWS.svg" },
      {
        title: "Azure Blob Storage",
        icon: "/images/technologies/cloud/Azure-Blob-Storage.svg",
      },
      {
        title: "Azure Data Lake",
        icon: "/images/technologies/cloud/Azure-Data-Lake.svg",
      },
      {
        title: "Azure DevOps",
        icon: "/images/technologies/cloud/Azure-DevOps.svg",
      },
      {
        title: "Azure Functions",
        icon: "/images/technologies/cloud/Azure-Functions.svg",
      },
      {
        title: "Azure IoT Hub",
        icon: "/images/technologies/cloud/Azure-IoT-Hub.svg",
      },
      {
        title: "Azure Notification Hub",
        icon: "/images/technologies/cloud/Azure-Notification-Hub.svg",
      },
      {
        title: "Azure Pipeline",
        icon: "/images/technologies/cloud/azure-pipline.svg",
      },
      {
        title: "Azure SQL Database",
        icon: "/images/technologies/cloud/Azure-SQL-Database.svg",
      },
      {
        title: "Azure Web Apps",
        icon: "/images/technologies/cloud/Azure-Web-Apps.svg",
      },
      {
        title: "DigitalOcean",
        icon: "/images/technologies/cloud/DigitalOcean.svg",
      },
      { title: "Docker", icon: "/images/technologies/cloud/Docker.svg" },
      { title: "Droplets", icon: "/images/technologies/cloud/Droplets.svg" },
      {
        title: "Google BigTable",
        icon: "/images/technologies/cloud/Google-BigTable.svg",
      },
      {
        title: "Google Cloud Datastore",
        icon: "/images/technologies/cloud/Google-Cloud-Datastore.svg",
      },
      {
        title: "Google Cloud IoT",
        icon: "/images/technologies/cloud/Google-Cloud-IoT.svg",
      },
      {
        title: "Google Cloud Platform",
        icon: "/images/technologies/cloud/Google-Cloud-Platform-GCP.svg",
      },
      {
        title: "Google Cloud SQL",
        icon: "/images/technologies/cloud/Google-Cloud-SQL.svg",
      },
      {
        title: "Kubernetes",
        icon: "/images/technologies/cloud/Kubernetes.svg",
      },
      {
        title: "Microsoft Azure App Insights",
        icon: "/images/technologies/cloud/Microsoft-Azure-Application-Insights.svg",
      },
      {
        title: "Microsoft Azure",
        icon: "/images/technologies/cloud/Microsoft-Azure.svg",
      },
      { title: "OpenShift", icon: "/images/technologies/cloud/OpenShift.svg" },
      {
        title: "PowerShell",
        icon: "/images/technologies/cloud/PowerShell.svg",
      },
      { title: "Terraform", icon: "/images/technologies/cloud/Terraform.svg" },
      { title: "Tesseract", icon: "/images/technologies/cloud/Tesseract.svg" },
      {
        title: "Virtual Machine",
        icon: "/images/technologies/cloud/Virtual-Machine.svg",
      },
    ],
    tech: [
      {
        title: "CI/CD & Automation",
        tools: [
          "GitHub Actions",
          "Gitlab CI",
          "CircleCI",
          "Jenkins",
          "TeamCity",
          "Drone CI",
          "Ansible",
          "Puppet",
          "Chef",
          "SaltStack",
          "Terraform",
          "Pulumi",
        ],
      },
      {
        title: "Containers & Orchestration",
        tools: [
          "Docker",
          "Docker Compose",
          "Kubernetes",
          "Helm",
          "OpenShift",
          "Rancher",
        ],
      },
      {
        title: "Monitoring & Logging",
        tools: [
          "Prometheus",
          "Grafana",
          "Datadog",
          "ELK Stack",
          "New Relic",
          "Sentry",
          "Logstash",
          "Fluentd",
        ],
      },
      {
        title: "Cloud Providers",
        tools: [
          "AWS",
          "Azure",
          "Google Cloud",
          "DigitalOcean",
          "Linode",
          "Heroku",
          "Vultr",
          "Netlify",
          "Vercel",
          "Render",
        ],
      },
      {
        title: "Cloud & Hosting",
        tools: [
          "AWS",
          "Azure",
          "Google Cloud",
          "DigitalOcean",
          "Heroku",
          "Netlify",
          "Vercel",
          "Linode",
          "Cloudflare",
        ],
      },
    ],
  },
  {
    title: "ERP&CRM",
    text: "Through Machine Learning Algorithms and AI, we help businesses leverage technologies to drive automation and improve experiences.",
    icon: "/images/features/chip.svg",
    stack: [
      {
        title: "4Hana Cloud Public",
        icon: "/images/technologies/erp/4Hana-Cloud-Public.svg",
      },
      { title: "Apex Code", icon: "/images/technologies/erp/Apex-code.svg" },
      {
        title: "Dynamics 365 Navision",
        icon: "/images/technologies/erp/Dynamics-365-Navision.svg",
      },
      { title: "HANA DB", icon: "/images/technologies/erp/HANA-DB.svg" },
      { title: "HTML", icon: "/images/technologies/erp/HTML.svg" },
      { title: "IXML", icon: "/images/technologies/erp/IXML.svg" },
      { title: "JavaScript", icon: "/images/technologies/erp/JavaScript.svg" },
      { title: "JSON", icon: "/images/technologies/erp/JSON.svg" },
      { title: "Level Up", icon: "/images/technologies/erp/Level-Up.svg" },
      {
        title: "Microsoft Azure Application Insights",
        icon: "/images/technologies/erp/Microsoft-Azure-Application-Insights.svg",
      },
      {
        title: "Microsoft Azure Monitor",
        icon: "/images/technologies/erp/Microsoft-Azure-Monitor.svg",
      },
      {
        title: "Microsoft Azure",
        icon: "/images/technologies/erp/Microsoft-Azure.svg",
      },
      {
        title: "Microsoft Power BI",
        icon: "/images/technologies/erp/Microsoft-Power-BI.svg",
      },
      {
        title: "Microsoft Teams",
        icon: "/images/technologies/erp/Microsoft-Teams.svg",
      },
      {
        title: "MS Dynamics 366",
        icon: "/images/technologies/erp/MS-Dynamics-366.svg",
      },
      { title: "Odoo", icon: "/images/technologies/erp/Odoo.svg" },
      {
        title: "Power Pages",
        icon: "/images/technologies/erp/Power-Pages.svg",
      },
      { title: "PowerApps", icon: "/images/technologies/erp/powerapps.svg" },
      { title: "Salesforce", icon: "/images/technologies/erp/salesforce.svg" },
      { title: "SAP CO", icon: "/images/technologies/erp/SAP-CO.svg" },
      { title: "SAP FI", icon: "/images/technologies/erp/SAP-FI.svg" },
      { title: "SAP FICO", icon: "/images/technologies/erp/SAP-FICO.svg" },
      { title: "SAP Fiori", icon: "/images/technologies/erp/SAP-Fiori.svg" },
      { title: "SAP HCM", icon: "/images/technologies/erp/SAP-HCM.svg" },
      { title: "SAP SD", icon: "/images/technologies/erp/SAP-SD.svg" },
      { title: "SAP UI5", icon: "/images/technologies/erp/SAP-UI5.svg" },
      { title: "SharePoint", icon: "/images/technologies/erp/SharePoint.svg" },
      { title: "XrmToolBox", icon: "/images/technologies/erp/XrmToolBox.svg" },
    ],
    tech: [
      {
        title: "SAP",
        tools: [
          "SAP ABAP 7.5+",
          "SAP UI5",
          "SAP Fiori",
          "JavaScript",
          "HTML",
          "XML",
          "JSON",
          "SAP S/4Hana (HANA DB, AMDP, CDS-extractors)",
          "SAP S/4Hana Cloud Public",
        ],
      },
      {
        title: "Dynamics 365",
        tools: [
          "XrmToolBox",
          "Level Up",
          "Sitemap Editor",
          "Azure",
          "Power Apps",
          "Power BI",
        ],
      },
      {
        title: "Odoo",
        tools: ["OdooRPC", "Odoo Mobile Framework"],
      },
      {
        title: "Salesforce",
        tools: [
          "Salesforce",
          "Apex code",
          "Visualforce",
          "Customer 360 Platform",
          "Lightning Web Components",
          "Site.com",
          "REST/SOAP API",
        ],
      },
    ],
  },
];
